<?php
/**
 * Created by PhpStorm.
 * User: quoctuan
 * Date: 3/4/18
 * Time: 1:12 PM
 */

namespace Quoctuan\Hello\Block;

use Magento\Framework\App\ObjectManager;
use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\Template;
use Magento\Store\Model\StoreManagerInterface;

class Index extends Template {
    protected $_objectManager;
    protected $_objectManagerInterface;

    public function __construct(Template\Context $context, array $data = []) {
        parent::__construct($context, $data);

        $this->_objectManager = ObjectManager::getInstance();
        $this->_objectManagerInterface = $this->_objectManager->get(StoreManagerInterface::class);
    }

    protected function _prepareLayout() {
        $this->assign("monan","Bún Bò");
        $this->setData("thucuong","Sting");

        $urlMedia = $this->_objectManagerInterface
                                            ->getStore()
                                            ->getBaseURL(UrlInterface::URL_TYPE_MEDIA);
        $this->setData('media',$urlMedia);

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function sayhello () {
        echo "Hello QuocTuan.Info";
    }
}