<?php
/**
 * Created by PhpStorm.
 * User: quoctuan
 * Date: 3/4/18
 * Time: 1:12 PM
 */

namespace Quoctuan\Hello\Block;

use Magento\Framework\View\Element\Template;

class Index extends Template {
    public function __construct(Template\Context $context, array $data = []) {
        parent::__construct($context, $data);
    }

    protected function _prepareLayout() {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function sayhello () {
        echo "Hello QuocTuan.Info";
    }
}